import Head from 'next/head';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';
import Project from '../components/Project';
import Work from '../components/Work';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Christopher | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Work />
      <Project />
      <Contact />
    </div>
  )
}
